version: "3.0"

services:
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    container_name: web
    image: web
    build:
      context: .
      dockerfile: src/PoohSticks.Web/Dockerfile
    ports:
      - 8080:8080
  service:
    container_name: service
    image: service
    build:
      context: .
      dockerfile: src/PoohSticks.Service/Dockerfile
    depends_on:
      - "postgres"
    restart: on-failure:5
volumes:
  pgdata:
    name: poohsticks-pgdata
